### ISSUE TITLE
这个计量单位是不是有点问题？

### ISSUE THREAD

**Issue by changcui** [LeiWang1999/tvm_gpu_gemm#1]
-result-

0.native_gemm.py：

average time cost of 10 runs = 2.15598 ms, 996.059 GFLOPS

1.blocked_gemm.py：

average time cost of 10 runs = 4865.28 ms, 1807.93 GFLOPS.

为什么 1.blocked_gemm.py 的时间是 0.native_gemm.py 的2000多倍？
如果改成 ns，又和后面的几个优化对不上。

**Comment by LeiWang1999** [comment]
native gemm worked in square size of (1024,1024, 1024) and the other four optimization workd in size of (16384, 16384, 16384).

```
最navie的情况，一个thread处理一个像素点的数据，这里我们选大小为1024的gemm为例子(因为这么做太慢了，大shape要跑很久)
```

**Comment by changcui** [comment]
Okay, got it.
